version: "3.7"

services:
  kong-database:
    image: postgres:12
    container_name: kong-database
    restart: always
    environment:
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kong
      POSTGRES_DB: api_gateway
    volumes:
      - kong_data:/var/lib/postgresql/data # 🔹 Persistencia de datos
    ports:
      - "5432:5432"
    networks:
      - kong-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kong"]
      interval: 10s
      retries: 5
      start_period: 10s

  kong-migrations:
    image: kong:latest
    container_name: kong-migrations
    restart: on-failure
    depends_on:
      kong-database:
        condition: service_healthy
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PG_DATABASE: api_gateway
    command: kong migrations bootstrap
    networks:
      - kong-net

  kong:
    image: kong:latest
    container_name: kong
    restart: always
    depends_on:
      kong-migrations:
        condition: service_completed_successfully
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PG_DATABASE: api_gateway
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_PROXY_LISTEN: 0.0.0.0:8000
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
    networks:
      - kong-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  konga:
    image: pantsel/konga
    container_name: konga
    restart: always
    depends_on:
      kong:
        condition: service_healthy
    environment:
      NODE_ENV: production
      DB_ADAPTER: postgres
      DB_HOST: kong-database
      DB_PORT: 5432
      DB_USER: kong
      DB_PASSWORD: kong
      DB_DATABASE: konga_db
    ports:
      - "1337:1337"
    networks:
      - kong-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:1337"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

networks:
  kong-net:
    driver: bridge

volumes:
  kong_data: # 🔹 Persistencia de PostgreSQL
    driver: local
